---
- name: Install submariner pre-reqs
  hosts: localhost
  gather_facts: yes
  vars_files: ../vars/vars.yml
  tasks:

  - name: Install subctl
    uri:
      url: "{{ subctl_cli_url }}"
      method: GET
  
  - name: Get path
    shell: echo $PATH:~/.local/bin
    register: path

  - name: Export submariner path
    ansible.builtin.lineinfile:
      path: ~/.profile
      line: "export PATH=$PATH:~/.local/bin"
